# Switch Class Driver
obj-$(CONFIG_SWITCH)		+= switch_class.o
obj-$(CONFIG_SWITCH_GPIO)	+= switch_gpio.o
obj-$(CONFIG_SWITCH_SKY)	+= switch_sky.o
# 20110703 hskim_wifi for wifi rpc (pantech_debug.c) to read nv mac address 
obj-$(CONFIG_MACH_MSM8X55_EF18K) += pansw_class.o
obj-$(CONFIG_MACH_MSM8X55_EF30S) += pansw_class.o
