#
# Copyright (c) 2010 Yamaha Corporation
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301,
# USA.
#

obj-$(CONFIG_EF18K_SENSORS_YAS529) += yas_mag_kernel_driver.o yas_ori_kernel_driver.o
obj-$(CONFIG_EF18K_SENSORS_BMA150) += yas_acc_kernel_driver.o
obj-$(CONFIG_EF18K_SENSORS_APDS9900) += apds9900.o proximity.o
obj-$(CONFIG_EF18K_SENSORS_L3G4200D) += yas_gyro_kernel_driver.o 

obj-$(CONFIG_EF30S_SENSORS_YAS529) += yas_mag_kernel_driver.o yas_ori_kernel_driver.o
obj-$(CONFIG_EF30S_SENSORS_BMA150) += yas_acc_kernel_driver.o
obj-$(CONFIG_EF30S_SENSORS_APDS9900) += apds9900.o proximity.o
obj-$(CONFIG_EF30S_SENSORS_L3G4200D) += yas_gyro_kernel_driver.o 

