/* Auto generated file by build command shell.
    !!!!!!!! Do not edit this file. !!!!!!!!
    Created time : Sun Jun 19 16:59:20 KST 2011
    Created by chero@pantech.com (GS1 Team)
*/
#ifndef BOARD_REV_H
#define BOARD_REV_H

#define PT20  0x01
#define PT30  0x02
#define WS10  0x04
#define WS20  0x08
#define ES10  0x10
#define ES20  0x20
#define TP10  0x40
#define TP20  0x80

#define BOARD_VER   WS20
#endif /*BOARD_REV_H*/
